
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: sleepdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  super_1:
    build:
      context: ./super_1
    container_name: sleep_tracker_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=sleepdb
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  pgdata:
